version: '3.1'

services:
  mongo:
    image: mongo
    container_name: molecules_mongo
    restart: always
    env_file:
      - ./environment/.env
    networks:
      - mongo-network
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    container_name: molecules_mongo_express
    restart: always
    ports:
      - "127.0.0.1:8081:8081"
    env_file:
      - ./environment/.env
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge

